version: '3.8'
services:
  meu-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
