version: '3.8'
services:
 cybernexus-frontend:
    build:
      context: .
      dockerfile: .Front-End/Dockerfile
    ports:
      - "4200:4200"
    networks:
      - cybernexus-rede

networks:
  cybernexus-rede:
    driver: bridge
