name: Build and Push Docker Images

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
     
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.USERNAME_DOCKER }}
        password: ${{ secrets.PASSWORD_DOKER }}
      
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./Front-End
        file: ./Front-End/Dockerfile
        push: true
        tags: cyberneexus/cybernexus-frontend:lastet
        
        
    - name: Set up GraalVM
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17.0.11'
        java-package: 'jdk' # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: 'x64' 

    - name: Print Java version
      run: java -version
      
    - name: Update HOST_BD 
      run: sed -i 's|<HOST_BD>|${{ secrets.HOST_BD }}|' ./Back-End/src/main/resources/application.properties
      
    - name: Update USERNAME_BD
      run: sed -i 's|<USERNAME_BD>|${{ secrets.USERNAME_BD }}|' ./Back-End/src/main/resources/application.properties

    - name: Update PASSWORD_BD
      run: sed -i 's|<PASSWORD_BD>|${{ secrets.PASSWORD_BD }}|' ./Back-End/src/main/resources/application.properties

    - name: Update HOST_MAIL 
      run: sed -i 's|<HOST_MAIL>|${{ secrets.HOST_MAIL }}|' ./Back-End/src/main/resources/application.properties

    - name: Update USERNAME_MAIL
      run: sed -i 's|<USERNAME_MAIL>|${{ secrets.USERNAME_MAIL }}|' ./Back-End/src/main/resources/application.properties

    - name: Update PASSWORD_MAIL
      run: sed -i 's|<PASSWORD_MAIL>|${{ secrets.PASSWORD_MAIL }}|' ./Back-End/src/main/resources/application.properties

   
   
    - name: Build with Maven
      run: mvn -f ./Back-End/pom.xml clean package

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./Back-End
        file: ./Back-End/Dockerfile
        push: true
        tags: cyberneexus/cybernexus-backend:lastet
        build-args: |
          HOST_BD=${{ secrets.HOST_BD }}
          USERNAME_BD=${{ secrets.USERNAME_BD }}
          PASSWORD_BD=${{ secrets.PASSWORD_BD }}
          HOST_MAIL=${{ secrets.HOST_MAIL }}
          USERNAME_MAIL=${{ secrets.USERNAME_MAIL }}
          PASSWORD_MAIL=${{ secrets.PASSWORD_MAIL }}
