name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.USERNAME_DOCKER }}
        password: ${{ secretsPASSWORD_DOCKER }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: cd cybernexus/Front-End
        file: \Dockerfile
        push: true
        tags: cyberneexus/cybernexus-frontend:latest

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: cd cybernexus/Back-End
        file: \Dockerfile
        push: true
        tags: cyberneexus/cybernexus-backend:latest
