# .github/workflows/main.yml
name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cyberneexus/cybernexus:latest

      - name: Deploy to Railway
        uses: railwayapp/github-action@v2
        with:
          apiKey: ${{ secrets.RAILWAY_API_KEY }}
          deploymentEnvironmentId: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
