# .github/workflows/main.yml
name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images for Back-End
        uses: docker/build-push-action@v2
        with:
          context: ./Back-End
          file: ./Back-End/Dockerfile
          push: true
          tags: cyberneexus/cybernexus-backend:latest

      - name: Build and push Docker images for Front-end
        uses: docker/build-push-action@v2
        with:
          context: ./Front-end
          file: ./Front-end/Dockerfile
          push: true
          tags: cyberneexus/cybernexus-frontend:latest

      - name: Deploy to Railway
        uses: railwayapp/github-action@v2
        with:
          apiKey: ${{ secrets.RAILWAY_API_KEY }}
          deploymentEnvironmentId: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
