name: Build and Push Docker Images

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.USERNAME_DOCKER }}
        password: ${{ secrets.PASSWORD_DOKER }}


        
    - name: Update HOST_BD 
      run: sed -i 's/<HOST_BD>/${{ secrets.HOST_BD }}'/src/main/resources/application.properties

    - name: Update USERNAME_BD
      run: sed -i 's/<USERNAME_BD>/${{ secrets.USERNAME_BD }}'/src/main/resources/application.properties

    - name: Update PASSWORD_BD
      run: sed -i 's/<PASSWORD_BD>/${{ secrets.PASSWORD_BD }}'/src/main/resources/application.properties

    - name: Update HOST_MAIL 
      run: sed -i 's/<HOST_MAIL>/${{ secrets.HOST_MAIL }}'/src/main/resources/application.properties

    - name: Update USERNAME_MAIL
      run: sed -i 's/<USERNAME_MAIL>/${{ secrets.USERNAME_MAIL }}'/src/main/resources/application.properties

    - name: Update PASSWORD_MAIL
      run: sed -i 's/<PASSWORD_MAIL>/${{ secrets.PASSWORD_MAIL }}'/src/main/resources/application.properties


    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./Front-End
        file: ./Front-End/Dockerfile
        push: true
        tags: cyberneexus/cybernexus-frontend:lastet

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./Back-End
        file: ./Back-End/Dockerfile
        push: true
        tags: cyberneexus/cybernexus-backend:lastet
