name: Build and Deploy to Railway
on:
  push:
    branches:
      - main  # substitua por sua branch de produção

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        cd Back-End
        mvn -B package --file pom.xml

    - name: Build Angular app
      run: |
        cd Front-End
        npm install
        npm run build -- --prod

    - name: Update HOST_BD 
      run: sed -i 's/<HOST_BD>/${{ secrets.HOST_BD }}/' src/main/resources/application.properties

    - name: Update USERNAME_BD
      run: sed -i 's/<USERNAME_BD>/${{ secrets.USERNAME_BD }}/' src/main/resources/application.properties

    - name: Update PASSWORD_BD
      run: sed -i 's/<PASSWORD_BD>/${{ secrets.PASSWORD_BD }}/' src/main/resources/application.properties

    - name: Update HOST_MAIL 
      run: sed -i 's/<HOST_MAIL>/${{ secrets.HOST_MAIL }}/' src/main/resources/application.properties

    - name: Update USERNAME_MAIL
      run: sed -i 's/<USERNAME_MAIL>/${{ secrets.USERNAME_MAIL }}/' src/main/resources/application.properties

    - name: Update PASSWORD_MAIL
      run: sed -i 's/<PASSWORD_MAIL>/${{ secrets.PASSWORD_MAIL }}/' src/main/resources/application.properties

    - name: Deploy to Railway
      uses: railwayapp/github-action@v2
      with:
        apiToken: ${{ secrets.RAILWAY_API_KEY }}
        projectId: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
