name: Build and Push Docker Images

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.USERNAME_DOCKER }}
        password: ${{ secrets.PASSWORD_DOKER }}


     


    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./Front-End
        file: ./Front-End/Dockerfile
        push: true
        tags: cyberneexus/cybernexus-frontend:lastet

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'slim'

    - name: Build with Maven
      run: mvn clean package

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ./Back-End
        file: ./Back-End/Dockerfile
        push: true
        tags: cyberneexus/cybernexus-backend:lastet
        build-args: |
          HOST_BD=${{ secrets.HOST_BD }}
          USERNAME_BD=${{ secrets.USERNAME_BD }}
          PASSWORD_BD=${{ secrets.PASSWORD_BD }}
          HOST_MAIL=${{ secrets.HOST_MAIL }}
          USERNAME_MAIL=${{ secrets.USERNAME_MAIL }}
          PASSWORD_MAIL=${{ secrets.PASSWORD_MAIL }}
