name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
         cd Back-End/.mvn/wrapper/
          mvn clean install

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1' # Atualizado para a versão correta do Node.js

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: |
          cd Front-End/src
          ng build --prod

      - name: Update application properties
        run: |
          sed -i 's/<HOST_BD>/${{ secrets.HOST_BD }}/' Back-End/src/main/resources/application.properties
          sed -i 's/<USERNAME_BD>/${{ secrets.USERNAME_BD }}/' Back-End/src/main/resources/application.properties
          sed -i 's/<PASSWORD_BD>/${{ secrets.PASSWORD_BD }}/' Back-End/src/main/resources/application.properties
          sed -i 's/<HOST_MAIL>/${{ secrets.HOST_MAIL }}/' Back-End/src/main/resources/application.properties
          sed -i 's/<USERNAME_MAIL>/${{ secrets.USERNAME_MAIL }}/' Back-End/src/main/resources/application.properties
          sed -i 's/<PASSWORD_MAIL>/${{ secrets.PASSWORD_MAIL }}/' Back-End/src/main/resources/application.properties

      - name: Build Docker image
        run: docker build -t cybernexus -f Back-End/Dockerfile .

      - name: Push to Railway
        uses: railwayapp/github-action@v2
        with:
          apiKey: ${{ secrets.RAILWAY_API_KEY }}
          deployment: cybernexus
